export const Props={
    url:{
         required:false,
         type:String,
     },
     multiple:{
         required:false,
         type:Boolean,
         default:true
     },
    mode:{
        type:String as ()=>'basic'|'advanced',
        required:false,
        default:'advanced'
    },
    accept:{
        required:false,
        type:String,
        default:"image/*"
    },
    maxFileSize:{
        required:false,
        type:Number,
        default:1020000,
    },
    auto:{
        type:Boolean,
        required:false,
         default:false,
    },
    chooseLabel:{
        type:String,
        required:false,
        default:'Choose'
    },
    name:{
        type:String
    }
}